[package]
name = "chokepoint"
version = "0.1.0"
edition = "2021"

[dependencies]
burster = "0.1.1"
bytes = "1.8.0"
chrono = "0.4.38"
eyre = "0.6.12"
futures = "0.3.31"
rand = "0.8.5"
rand_distr = "0.4.3"
tokio = { version = "1.41.1", features = ["time", "sync"] }
tokio-util = { version = "0.7.12", features = ["time"] }
tracing = "0.1.40"

[dev-dependencies]
color-eyre = "0.6.3"
tokio = { version = "1.41.1", features = ["time", "sync", "rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.18"
tracing-test = "0.2.5"
