[package]
name = "chokepoint"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
futures = "0.3.31"
tokio = "1.41.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tracing-test = "0.2.5"
